export type AccessPolicyAvailabilityStatus =
    | 'publicIgnored'
    | 'authenticatedAvailable'
    | 'authenticatedMissing'
    | 'ipRestrictedAvailable'
    | 'ipRestrictedMissing'
    | 'ipRestrictedBlocksAll'
    | 'combinedAllAvailable'
    | 'combinedAllMissingAuth'
    | 'combinedAllMissingIp'
    | 'combinedAllMissingBoth'
    | 'combinedAllIpBlocksAll'
    | 'combinedAnyAvailableAuth'
    | 'combinedAnyAvailableIp'
    | 'combinedAnyAvailableBoth'
    | 'combinedAnyIpBlocksAll'
    | 'combinedAnyMissing'
