import { z } from 'zod'

export const commandSchema = z.strictObject({
    runId: z.string().regex(/^[a-z0-9]{8,32}$/u),
    phase: z.enum([
        'prepare',
        'proxy-update',
        'proxy-disable',
        'proxy-enable',
        'rapid-update',
        'create-temporary',
        'delete-temporary',
        'redirect-update',
        'redirect-disable',
        'redirect-enable',
        'redirect-delete',
        'policy-update',
        'snapshot',
        'certificates-read',
        'certificate-import',
        'certificate-request',
        'certificate-renew',
        'certificate-bind',
        'binding-request',
        'binding-retry',
        'certificate-delete',
        'durability-read',
        'jobs-read',
        'crowdsec-update',
        'crowdsec-disable',
        'forward-auth',
        'npm-import',
        'scale-create',
        'scale-update',
        'scale-read',
        'scale-delete',
        'scale-trusted-upstream',
        'scale-npm-import',
    ]),
    upstreamPort: z.number().int().min(1).max(65535),
    secondaryPort: z.number().int().min(1).max(65535),
    iteration: z.number().int().min(0).max(10000).default(0),
    concurrency: z.number().int().min(1).max(8).default(1),
    hostCount: z.number().int().min(1).max(100).default(100),
    seed: z.number().int().min(0).max(0xffffffff).default(70),
    trustedUpstreamPort: z.number().int().min(1).max(65535).optional(),
    resetTls: z.boolean().default(false),
    interruptedApply: z.boolean().default(false),
    certificateDomain: z
        .string()
        .max(253)
        .regex(/^(?:[a-z0-9](?:[a-z0-9-]{0,61}[a-z0-9])?\.)+[a-z]{2,63}$/u)
        .optional(),
    certificateEnvironment: z.enum(['staging', 'production']).default('staging'),
    certificateId: z.uuid().optional(),
    authPort: z.number().int().min(1).max(65535).optional(),
    forwardAuthCombined: z.boolean().default(false),
    policyMode: z.enum(['public', 'authenticated', 'ip-restricted']).default('public'),
})

export const stateSchema = z.strictObject({
    runId: z.string().regex(/^[a-z0-9]{8,32}$/u),
    domain: commandSchema.shape.certificateDomain,
    session: z.string().min(1).max(256).optional(),
    proxyId: z.uuid().optional(),
    policyId: z.uuid().optional(),
    policyHostId: z.uuid().optional(),
    redirectId: z.uuid().optional(),
    temporaryId: z.uuid().optional(),
    accountId: z.uuid().optional(),
    certificateId: z.uuid().optional(),
    jobId: z.uuid().optional(),
    npmHistoryId: z.uuid().optional(),
    npmRetryHistoryId: z.uuid().optional(),
})
