**
!controller/
!controller/Cargo.toml
!controller/Cargo.lock
!controller/src/
!controller/src/**

!docker/
!docker/crowdsec/
!docker/crowdsec/tooling/
!docker/crowdsec/tooling/caddy-http-only.sh
!docker/licenses/
!docker/licenses/Caddy-LICENSE
!docker/licenses/CaddyCrowdSecBouncer-NOTICE
