**
!core/
!core/Cargo.toml
!core/Cargo.lock
!core/src/
!core/src/**

!docker/
!docker/caddy/
!docker/caddy/tooling/
!docker/caddy/tooling/verify-buildinfo.sh
!docker/crowdsec/
!docker/crowdsec/tooling/
!docker/crowdsec/tooling/caddy-http-only.sh
!docker/licenses/
!docker/licenses/Caddy-LICENSE
!docker/licenses/CaddyCrowdSecBouncer-NOTICE
