import { PERMISSIONS, PERMISSION_REGISTRY, SYSTEM_ROLES } from '@/config/permissions.config.ts'
import type { PermissionKey, SystemRoleKey } from '@/shared/Types/permissions-config.types.ts'
const allPermissionKeys = PERMISSION_REGISTRY.map((permission) => permission.key)

export const SYSTEM_ROLE_REGISTRY = [
    {
        key: SYSTEM_ROLES.OWNER,
        name: 'Owner',
        description: 'Built-in role with every registered permission.',
        permissionKeys: allPermissionKeys,
    },
    {
        key: SYSTEM_ROLES.ADMIN,
        name: 'Administrator',
        description: 'Built-in role for user and custom-role administration without owner powers.',
        permissionKeys: [
            PERMISSIONS.APP_ACCESS,
            PERMISSIONS.PROXY_HOSTS_VIEW,
            PERMISSIONS.PROXY_HOSTS_CREATE,
            PERMISSIONS.PROXY_HOSTS_UPDATE,
            PERMISSIONS.PROXY_HOSTS_DELETE,
            PERMISSIONS.PROXY_HOSTS_ENABLE,
            PERMISSIONS.PROXY_HOSTS_DISABLE,
            PERMISSIONS.PROXY_HOSTS_APPLY,
            PERMISSIONS.REDIRECT_HOSTS_VIEW,
            PERMISSIONS.REDIRECT_HOSTS_CREATE,
            PERMISSIONS.REDIRECT_HOSTS_UPDATE,
            PERMISSIONS.REDIRECT_HOSTS_DELETE,
            PERMISSIONS.REDIRECT_HOSTS_ENABLE,
            PERMISSIONS.REDIRECT_HOSTS_DISABLE,
            PERMISSIONS.REDIRECT_HOSTS_APPLY,
            PERMISSIONS.CERTIFICATES_VIEW,
            PERMISSIONS.CERTIFICATES_CREATE,
            PERMISSIONS.CERTIFICATES_UPDATE,
            PERMISSIONS.CERTIFICATES_DELETE,
            PERMISSIONS.CERTIFICATES_ISSUE,
            PERMISSIONS.CERTIFICATES_RENEW,
            PERMISSIONS.TRUSTED_CAS_VIEW,
            PERMISSIONS.TRUSTED_CAS_CREATE,
            PERMISSIONS.TRUSTED_CAS_UPDATE,
            PERMISSIONS.TRUSTED_CAS_DELETE,
            PERMISSIONS.USERS_VIEW,
            PERMISSIONS.USERS_CREATE,
            PERMISSIONS.USERS_UPDATE,
            PERMISSIONS.USERS_DISABLE,
            PERMISSIONS.USERS_ENABLE,
            PERMISSIONS.USERS_ASSIGN_ROLES,
            PERMISSIONS.ROLES_VIEW,
            PERMISSIONS.ROLES_CREATE,
            PERMISSIONS.ROLES_UPDATE,
            PERMISSIONS.ROLES_DELETE,
            PERMISSIONS.ROLES_ASSIGN_PERMISSIONS,
            PERMISSIONS.ACCESS_POLICIES_VIEW,
            PERMISSIONS.ACCESS_POLICIES_CREATE,
            PERMISSIONS.ACCESS_POLICIES_UPDATE,
            PERMISSIONS.ACCESS_POLICIES_DELETE,
            PERMISSIONS.ACCESS_POLICIES_ASSIGN,
            PERMISSIONS.ACCESS_POLICIES_APPLY,
            PERMISSIONS.PROXY_ACCESS_LOGS_VIEW,
            PERMISSIONS.CROWDSEC_VIEW,
            PERMISSIONS.CROWDSEC_UPDATE,
            PERMISSIONS.SYSTEM_APPEARANCE_UPDATE,
            PERMISSIONS.DEFAULT_SITE_VIEW,
            PERMISSIONS.DEFAULT_SITE_UPDATE,
            PERMISSIONS.AUDIT_LOGS_VIEW,
            PERMISSIONS.NPM_IMPORT,
            PERMISSIONS.MIGRATION,
            PERMISSIONS.ACCOUNT_VIEW,
            PERMISSIONS.ACCOUNT_UPDATE,
        ],
    },
    {
        key: SYSTEM_ROLES.VIEWER,
        name: 'Viewer',
        description: 'Built-in role for basic application and account access.',
        permissionKeys: [
            PERMISSIONS.APP_ACCESS,
            PERMISSIONS.PROXY_HOSTS_VIEW,
            PERMISSIONS.REDIRECT_HOSTS_VIEW,
            PERMISSIONS.CERTIFICATES_VIEW,
            PERMISSIONS.TRUSTED_CAS_VIEW,
            PERMISSIONS.CROWDSEC_VIEW,
            PERMISSIONS.ACCOUNT_VIEW,
            PERMISSIONS.ACCOUNT_UPDATE,
        ],
    },
] as const satisfies ReadonlyArray<{
    key: SystemRoleKey
    name: string
    description: string
    permissionKeys: ReadonlyArray<PermissionKey>
}>
