*

!package.json
!bun.lock

!controller/
!controller/Cargo.toml
!controller/Cargo.lock
!controller/src/
!controller/src/**

!docker/
!docker/web/
!docker/web/**
!docker/production/
!docker/production/entrypoint.sh

!scripts/
!scripts/**

!web/
!web/**

web/dist/
web/node_modules/
controller/target/
node_modules/
.cache/
**/.env
**/.env.*
**/*.key
**/*.key.pem
**/*.log
