export const AUDIT_ACTOR_KINDS = ['user', 'anonymous', 'system'] as const
export const AUDIT_RESULTS = ['success', 'failure', 'denied'] as const

export const AUDIT_ACTIONS = [
    'login',
    'logout',
    'create',
    'update',
    'delete',
    'enable',
    'disable',
    'rotate',
    'reset',
    'accept',
    'reauthenticate',
    'import',
    'replace',
    'request',
    'renew',
    'save',
    'apply',
    'accepted',
    'started',
    'issued',
    'activated',
    'renewed',
    'retry_scheduled',
    'failed',
] as const

export const AUDIT_RESOURCES = [
    'session',
    'password',
    'totp',
    'recovery-codes',
    'passkey',
    'invite',
    'setup',
    'security-settings',
    'user',
    'role',
    'proxy-host',
    'redirect-host',
    'access-policy',
    'basic-auth-account',
    'certificate',
    'trusted-ca',
    'proxy-runtime-settings',
    'proxy-host-settings',
    'proxy-runtime',
    'crowdsec',
    'npm-import',
    'config-import',
    'config-export',
] as const

export const AUDIT_AUTHENTICATION_METHODS = [
    'password',
    'totp',
    'recovery-code',
    'passkey',
    'invite',
    'setup',
] as const

export const AUDIT_FAILURE_CODES = [
    'authentication_failed',
    'permission_denied',
    'invalid_input',
    'not_found',
    'conflict',
    'reauthentication_required',
    'service_unavailable',
    'challenge_expired',
    'invalid_or_expired_token',
    'runtime_pending',
    'runtime_failed',
] as const

export const AUDIT_CHANGED_FIELDS = [
    'displayName',
    'email',
    'status',
    'roles',
    'permissions',
    'name',
    'description',
    'mode',
    'combination',
    'ipRules',
    'forwardAuth',
    'basicAuth',
    'domains',
    'upstream',
    'tls',
    'headers',
    'certificate',
    'trustedCa',
    'accessPolicy',
    'security',
] as const
