import type { PermissionKey } from '@/config/Types/permissions-config.types.ts'
export const PERMISSIONS = {
    APP_ACCESS: 'app.access',
    PROXY_HOSTS_VIEW: 'proxy_hosts.view',
    PROXY_HOSTS_CREATE: 'proxy_hosts.create',
    PROXY_HOSTS_UPDATE: 'proxy_hosts.update',
    PROXY_HOSTS_DELETE: 'proxy_hosts.delete',
    PROXY_HOSTS_ENABLE: 'proxy_hosts.enable',
    PROXY_HOSTS_DISABLE: 'proxy_hosts.disable',
    PROXY_HOSTS_APPLY: 'proxy_hosts.apply',
    REDIRECT_HOSTS_VIEW: 'redirect_hosts.view',
    REDIRECT_HOSTS_CREATE: 'redirect_hosts.create',
    REDIRECT_HOSTS_UPDATE: 'redirect_hosts.update',
    REDIRECT_HOSTS_DELETE: 'redirect_hosts.delete',
    REDIRECT_HOSTS_ENABLE: 'redirect_hosts.enable',
    REDIRECT_HOSTS_DISABLE: 'redirect_hosts.disable',
    REDIRECT_HOSTS_APPLY: 'redirect_hosts.apply',
    CERTIFICATES_VIEW: 'certificates.view',
    CERTIFICATES_CREATE: 'certificates.create',
    CERTIFICATES_UPDATE: 'certificates.update',
    CERTIFICATES_DELETE: 'certificates.delete',
    CERTIFICATES_ISSUE: 'certificates.issue',
    CERTIFICATES_RENEW: 'certificates.renew',
    TRUSTED_CAS_VIEW: 'trusted_cas.view',
    TRUSTED_CAS_CREATE: 'trusted_cas.create',
    TRUSTED_CAS_UPDATE: 'trusted_cas.update',
    TRUSTED_CAS_DELETE: 'trusted_cas.delete',
    USERS_VIEW: 'users.view',
    USERS_CREATE: 'users.create',
    USERS_UPDATE: 'users.update',
    USERS_DISABLE: 'users.disable',
    USERS_ENABLE: 'users.enable',
    USERS_ASSIGN_ROLES: 'users.assign_roles',
    ROLES_VIEW: 'roles.view',
    ROLES_CREATE: 'roles.create',
    ROLES_UPDATE: 'roles.update',
    ROLES_DELETE: 'roles.delete',
    ROLES_ASSIGN_PERMISSIONS: 'roles.assign_permissions',
    ACCESS_POLICIES_VIEW: 'access_policies.view',
    ACCESS_POLICIES_CREATE: 'access_policies.create',
    ACCESS_POLICIES_UPDATE: 'access_policies.update',
    ACCESS_POLICIES_DELETE: 'access_policies.delete',
    ACCESS_POLICIES_ASSIGN: 'access_policies.assign',
    ACCESS_POLICIES_APPLY: 'access_policies.apply',
    PROXY_ACCESS_LOGS_VIEW: 'proxy-access-logs:view',
    CROWDSEC_VIEW: 'crowdsec.view',
    CROWDSEC_UPDATE: 'crowdsec.update',
    DEFAULT_SITE_VIEW: 'default_site.view',
    DEFAULT_SITE_UPDATE: 'default_site.update',
    AUDIT_LOGS_VIEW: 'audit-logs:view',
    NPM_IMPORT: 'system.npm_import',
    MIGRATION: 'system.migration',
    ACCOUNT_VIEW: 'account.view',
    ACCOUNT_UPDATE: 'account.update',
} as const

export const RUNTIME_SUPPORT_REPORT_PERMISSIONS = [
    PERMISSIONS.PROXY_HOSTS_VIEW,
    PERMISSIONS.REDIRECT_HOSTS_VIEW,
    PERMISSIONS.CERTIFICATES_VIEW,
] as const

export const PERMISSION_REGISTRY = [
    { key: PERMISSIONS.APP_ACCESS, name: 'Application access' },
    { key: PERMISSIONS.PROXY_HOSTS_VIEW, name: 'View proxy hosts' },
    { key: PERMISSIONS.PROXY_HOSTS_CREATE, name: 'Create proxy hosts' },
    { key: PERMISSIONS.PROXY_HOSTS_UPDATE, name: 'Update proxy hosts' },
    { key: PERMISSIONS.PROXY_HOSTS_DELETE, name: 'Delete proxy hosts' },
    { key: PERMISSIONS.PROXY_HOSTS_ENABLE, name: 'Enable proxy hosts' },
    { key: PERMISSIONS.PROXY_HOSTS_DISABLE, name: 'Disable proxy hosts' },
    { key: PERMISSIONS.PROXY_HOSTS_APPLY, name: 'Apply proxy configuration' },
    { key: PERMISSIONS.REDIRECT_HOSTS_VIEW, name: 'View redirect hosts' },
    { key: PERMISSIONS.REDIRECT_HOSTS_CREATE, name: 'Create redirect hosts' },
    { key: PERMISSIONS.REDIRECT_HOSTS_UPDATE, name: 'Update redirect hosts' },
    { key: PERMISSIONS.REDIRECT_HOSTS_DELETE, name: 'Delete redirect hosts' },
    { key: PERMISSIONS.REDIRECT_HOSTS_ENABLE, name: 'Enable redirect hosts' },
    { key: PERMISSIONS.REDIRECT_HOSTS_DISABLE, name: 'Disable redirect hosts' },
    { key: PERMISSIONS.REDIRECT_HOSTS_APPLY, name: 'Apply redirect configuration' },
    { key: PERMISSIONS.CERTIFICATES_VIEW, name: 'View certificates' },
    { key: PERMISSIONS.CERTIFICATES_CREATE, name: 'Import certificates' },
    { key: PERMISSIONS.CERTIFICATES_UPDATE, name: 'Replace manual certificates' },
    { key: PERMISSIONS.CERTIFICATES_DELETE, name: 'Delete unused certificates' },
    { key: PERMISSIONS.CERTIFICATES_ISSUE, name: 'Request ACME certificates' },
    { key: PERMISSIONS.CERTIFICATES_RENEW, name: 'Renew ACME certificates' },
    { key: PERMISSIONS.TRUSTED_CAS_VIEW, name: 'View trusted CAs' },
    { key: PERMISSIONS.TRUSTED_CAS_CREATE, name: 'Import trusted CAs' },
    { key: PERMISSIONS.TRUSTED_CAS_UPDATE, name: 'Replace trusted CA bundles' },
    { key: PERMISSIONS.TRUSTED_CAS_DELETE, name: 'Delete unused trusted CAs' },
    { key: PERMISSIONS.USERS_VIEW, name: 'View users' },
    { key: PERMISSIONS.USERS_CREATE, name: 'Create users' },
    { key: PERMISSIONS.USERS_UPDATE, name: 'Update users' },
    { key: PERMISSIONS.USERS_DISABLE, name: 'Disable users' },
    { key: PERMISSIONS.USERS_ENABLE, name: 'Enable users' },
    { key: PERMISSIONS.USERS_ASSIGN_ROLES, name: 'Assign user roles' },
    { key: PERMISSIONS.ROLES_VIEW, name: 'View roles' },
    { key: PERMISSIONS.ROLES_CREATE, name: 'Create roles' },
    { key: PERMISSIONS.ROLES_UPDATE, name: 'Update roles' },
    { key: PERMISSIONS.ROLES_DELETE, name: 'Delete roles' },
    {
        key: PERMISSIONS.ROLES_ASSIGN_PERMISSIONS,
        name: 'Assign role permissions',
    },
    { key: PERMISSIONS.ACCESS_POLICIES_VIEW, name: 'View access policies' },
    { key: PERMISSIONS.ACCESS_POLICIES_CREATE, name: 'Create access policies' },
    { key: PERMISSIONS.ACCESS_POLICIES_UPDATE, name: 'Update access policies' },
    { key: PERMISSIONS.ACCESS_POLICIES_DELETE, name: 'Delete access policies' },
    { key: PERMISSIONS.ACCESS_POLICIES_ASSIGN, name: 'Assign access policies' },
    { key: PERMISSIONS.ACCESS_POLICIES_APPLY, name: 'Apply access policies' },
    { key: PERMISSIONS.PROXY_ACCESS_LOGS_VIEW, name: 'View proxy access logs' },
    { key: PERMISSIONS.CROWDSEC_VIEW, name: 'View CrowdSec configuration' },
    { key: PERMISSIONS.CROWDSEC_UPDATE, name: 'Update CrowdSec configuration' },
    { key: PERMISSIONS.DEFAULT_SITE_VIEW, name: 'View default site settings' },
    { key: PERMISSIONS.DEFAULT_SITE_UPDATE, name: 'Update default site settings' },
    { key: PERMISSIONS.AUDIT_LOGS_VIEW, name: 'View audit log' },
    { key: PERMISSIONS.NPM_IMPORT, name: 'Import from Nginx Proxy Manager' },
    { key: PERMISSIONS.MIGRATION, name: 'Import and export configuration' },
    { key: PERMISSIONS.ACCOUNT_VIEW, name: 'View own account' },
    { key: PERMISSIONS.ACCOUNT_UPDATE, name: 'Update own account' },
] as const satisfies ReadonlyArray<{ key: PermissionKey; name: string }>

export const SYSTEM_ROLES = {
    OWNER: 'owner',
    ADMIN: 'admin',
    VIEWER: 'viewer',
} as const
