export const PROFILE_IMAGE_ACCEPTED_MIME_TYPES = ['image/jpeg', 'image/png', 'image/webp'] as const

export const PROFILE_IMAGE_ACCEPT = PROFILE_IMAGE_ACCEPTED_MIME_TYPES.join(',')
export const PROFILE_IMAGE_CLIENT_OUTPUT_SIZE = 512
export const PROFILE_IMAGE_SERVER_OUTPUT_SIZE = 256
export const PROFILE_IMAGE_MAX_SOURCE_BYTES = 8 * 1_024 * 1_024
export const PROFILE_IMAGE_MAX_SOURCE_PIXELS = 40_000_000
export const PROFILE_IMAGE_MAX_INPUT_PIXELS = 4_000_000
export const PROFILE_IMAGE_MAX_DATA_URL_LENGTH = 4 * 1_024 * 1_024
export const PROFILE_IMAGE_MAX_WEBP_BYTES = 256 * 1_024
export const PROFILE_IMAGE_VERSION_QUERY_KEY = 'v'
