export const QUICK_SEARCH_LIMIT = 6
export const QUICK_SEARCH_NAVIGATION_LIMIT = 8
export const QUICK_SEARCH_MIN_QUERY_LENGTH = 2
export const QUICK_SEARCH_MAX_QUERY_LENGTH = 128
export const QUICK_SEARCH_DEBOUNCE_MS = 200
