/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as AuthenticatedRouteRouteImport } from './routes/_authenticated/route'
import { Route as PublicRouteRouteImport } from './routes/_public/route'
import { Route as AuthenticatedIndexRouteImport } from './routes/_authenticated/index'
import { Route as AuthenticatedAccessPoliciesRouteImport } from './routes/_authenticated/access-policies'
import { Route as AuthenticatedAccountRouteImport } from './routes/_authenticated/account'
import { Route as AuthenticatedCertificatesRouteImport } from './routes/_authenticated/certificates'
import { Route as AuthenticatedProxyAccessLogsRouteImport } from './routes/_authenticated/proxy-access-logs'
import { Route as AuthenticatedProxyHostsRouteImport } from './routes/_authenticated/proxy-hosts'
import { Route as AuthenticatedRedirectHostsRouteImport } from './routes/_authenticated/redirect-hosts'
import { Route as AuthenticatedRolesRouteImport } from './routes/_authenticated/roles'
import { Route as AuthenticatedUsersRouteImport } from './routes/_authenticated/users'
import { Route as PublicAcceptInviteRouteImport } from './routes/_public/accept-invite'
import { Route as PublicForgotPasswordRouteImport } from './routes/_public/forgot-password'
import { Route as PublicLoginRouteImport } from './routes/_public/login'
import { Route as PublicResetPasswordRouteImport } from './routes/_public/reset-password'
import { Route as PublicSetupRouteImport } from './routes/_public/setup'
import { Route as HealthLiveRouteImport } from './routes/health/live'
import { Route as HealthReadyRouteImport } from './routes/health/ready'
import { Route as PublicLoginIndexRouteImport } from './routes/_public/login.index'
import { Route as PublicLoginTwoFactorRouteImport } from './routes/_public/login.two-factor'
import { Route as MediaAvatarsUserIdRouteImport } from './routes/media/avatars/$userId'

const AuthenticatedRouteRoute = AuthenticatedRouteRouteImport.update({
  id: '/_authenticated',
  getParentRoute: () => rootRouteImport,
} as any)
const PublicRouteRoute = PublicRouteRouteImport.update({
  id: '/_public',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedIndexRoute = AuthenticatedIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedAccessPoliciesRoute =
  AuthenticatedAccessPoliciesRouteImport.update({
    id: '/access-policies',
    path: '/access-policies',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedAccountRoute = AuthenticatedAccountRouteImport.update({
  id: '/account',
  path: '/account',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedCertificatesRoute =
  AuthenticatedCertificatesRouteImport.update({
    id: '/certificates',
    path: '/certificates',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedProxyAccessLogsRoute =
  AuthenticatedProxyAccessLogsRouteImport.update({
    id: '/proxy-access-logs',
    path: '/proxy-access-logs',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedProxyHostsRoute = AuthenticatedProxyHostsRouteImport.update({
  id: '/proxy-hosts',
  path: '/proxy-hosts',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedRedirectHostsRoute =
  AuthenticatedRedirectHostsRouteImport.update({
    id: '/redirect-hosts',
    path: '/redirect-hosts',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedRolesRoute = AuthenticatedRolesRouteImport.update({
  id: '/roles',
  path: '/roles',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedUsersRoute = AuthenticatedUsersRouteImport.update({
  id: '/users',
  path: '/users',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const PublicAcceptInviteRoute = PublicAcceptInviteRouteImport.update({
  id: '/accept-invite',
  path: '/accept-invite',
  getParentRoute: () => PublicRouteRoute,
} as any)
const PublicForgotPasswordRoute = PublicForgotPasswordRouteImport.update({
  id: '/forgot-password',
  path: '/forgot-password',
  getParentRoute: () => PublicRouteRoute,
} as any)
const PublicLoginRoute = PublicLoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => PublicRouteRoute,
} as any)
const PublicResetPasswordRoute = PublicResetPasswordRouteImport.update({
  id: '/reset-password',
  path: '/reset-password',
  getParentRoute: () => PublicRouteRoute,
} as any)
const PublicSetupRoute = PublicSetupRouteImport.update({
  id: '/setup',
  path: '/setup',
  getParentRoute: () => PublicRouteRoute,
} as any)
const HealthLiveRoute = HealthLiveRouteImport.update({
  id: '/health/live',
  path: '/health/live',
  getParentRoute: () => rootRouteImport,
} as any)
const HealthReadyRoute = HealthReadyRouteImport.update({
  id: '/health/ready',
  path: '/health/ready',
  getParentRoute: () => rootRouteImport,
} as any)
const PublicLoginIndexRoute = PublicLoginIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => PublicLoginRoute,
} as any)
const PublicLoginTwoFactorRoute = PublicLoginTwoFactorRouteImport.update({
  id: '/two-factor',
  path: '/two-factor',
  getParentRoute: () => PublicLoginRoute,
} as any)
const MediaAvatarsUserIdRoute = MediaAvatarsUserIdRouteImport.update({
  id: '/media/avatars/$userId',
  path: '/media/avatars/$userId',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof AuthenticatedIndexRoute
  '/access-policies': typeof AuthenticatedAccessPoliciesRoute
  '/account': typeof AuthenticatedAccountRoute
  '/certificates': typeof AuthenticatedCertificatesRoute
  '/proxy-access-logs': typeof AuthenticatedProxyAccessLogsRoute
  '/proxy-hosts': typeof AuthenticatedProxyHostsRoute
  '/redirect-hosts': typeof AuthenticatedRedirectHostsRoute
  '/roles': typeof AuthenticatedRolesRoute
  '/users': typeof AuthenticatedUsersRoute
  '/accept-invite': typeof PublicAcceptInviteRoute
  '/forgot-password': typeof PublicForgotPasswordRoute
  '/login': typeof PublicLoginRouteWithChildren
  '/reset-password': typeof PublicResetPasswordRoute
  '/setup': typeof PublicSetupRoute
  '/health/live': typeof HealthLiveRoute
  '/health/ready': typeof HealthReadyRoute
  '/login/two-factor': typeof PublicLoginTwoFactorRoute
  '/media/avatars/$userId': typeof MediaAvatarsUserIdRoute
  '/login/': typeof PublicLoginIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof AuthenticatedIndexRoute
  '/access-policies': typeof AuthenticatedAccessPoliciesRoute
  '/account': typeof AuthenticatedAccountRoute
  '/certificates': typeof AuthenticatedCertificatesRoute
  '/proxy-access-logs': typeof AuthenticatedProxyAccessLogsRoute
  '/proxy-hosts': typeof AuthenticatedProxyHostsRoute
  '/redirect-hosts': typeof AuthenticatedRedirectHostsRoute
  '/roles': typeof AuthenticatedRolesRoute
  '/users': typeof AuthenticatedUsersRoute
  '/accept-invite': typeof PublicAcceptInviteRoute
  '/forgot-password': typeof PublicForgotPasswordRoute
  '/reset-password': typeof PublicResetPasswordRoute
  '/setup': typeof PublicSetupRoute
  '/health/live': typeof HealthLiveRoute
  '/health/ready': typeof HealthReadyRoute
  '/login/two-factor': typeof PublicLoginTwoFactorRoute
  '/media/avatars/$userId': typeof MediaAvatarsUserIdRoute
  '/login': typeof PublicLoginIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/_authenticated': typeof AuthenticatedRouteRouteWithChildren
  '/_public': typeof PublicRouteRouteWithChildren
  '/_authenticated/access-policies': typeof AuthenticatedAccessPoliciesRoute
  '/_authenticated/account': typeof AuthenticatedAccountRoute
  '/_authenticated/certificates': typeof AuthenticatedCertificatesRoute
  '/_authenticated/proxy-access-logs': typeof AuthenticatedProxyAccessLogsRoute
  '/_authenticated/proxy-hosts': typeof AuthenticatedProxyHostsRoute
  '/_authenticated/redirect-hosts': typeof AuthenticatedRedirectHostsRoute
  '/_authenticated/roles': typeof AuthenticatedRolesRoute
  '/_authenticated/users': typeof AuthenticatedUsersRoute
  '/_public/accept-invite': typeof PublicAcceptInviteRoute
  '/_public/forgot-password': typeof PublicForgotPasswordRoute
  '/_public/login': typeof PublicLoginRouteWithChildren
  '/_public/reset-password': typeof PublicResetPasswordRoute
  '/_public/setup': typeof PublicSetupRoute
  '/health/live': typeof HealthLiveRoute
  '/health/ready': typeof HealthReadyRoute
  '/_authenticated/': typeof AuthenticatedIndexRoute
  '/_public/login/two-factor': typeof PublicLoginTwoFactorRoute
  '/media/avatars/$userId': typeof MediaAvatarsUserIdRoute
  '/_public/login/': typeof PublicLoginIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/access-policies'
    | '/account'
    | '/certificates'
    | '/proxy-access-logs'
    | '/proxy-hosts'
    | '/redirect-hosts'
    | '/roles'
    | '/users'
    | '/accept-invite'
    | '/forgot-password'
    | '/login'
    | '/reset-password'
    | '/setup'
    | '/health/live'
    | '/health/ready'
    | '/login/two-factor'
    | '/media/avatars/$userId'
    | '/login/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/access-policies'
    | '/account'
    | '/certificates'
    | '/proxy-access-logs'
    | '/proxy-hosts'
    | '/redirect-hosts'
    | '/roles'
    | '/users'
    | '/accept-invite'
    | '/forgot-password'
    | '/reset-password'
    | '/setup'
    | '/health/live'
    | '/health/ready'
    | '/login/two-factor'
    | '/media/avatars/$userId'
    | '/login'
  id:
    | '__root__'
    | '/_authenticated'
    | '/_public'
    | '/_authenticated/access-policies'
    | '/_authenticated/account'
    | '/_authenticated/certificates'
    | '/_authenticated/proxy-access-logs'
    | '/_authenticated/proxy-hosts'
    | '/_authenticated/redirect-hosts'
    | '/_authenticated/roles'
    | '/_authenticated/users'
    | '/_public/accept-invite'
    | '/_public/forgot-password'
    | '/_public/login'
    | '/_public/reset-password'
    | '/_public/setup'
    | '/health/live'
    | '/health/ready'
    | '/_authenticated/'
    | '/_public/login/two-factor'
    | '/media/avatars/$userId'
    | '/_public/login/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  AuthenticatedRouteRoute: typeof AuthenticatedRouteRouteWithChildren
  PublicRouteRoute: typeof PublicRouteRouteWithChildren
  HealthLiveRoute: typeof HealthLiveRoute
  HealthReadyRoute: typeof HealthReadyRoute
  MediaAvatarsUserIdRoute: typeof MediaAvatarsUserIdRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/_authenticated': {
      id: '/_authenticated'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof AuthenticatedRouteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_public': {
      id: '/_public'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof PublicRouteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated/': {
      id: '/_authenticated/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof AuthenticatedIndexRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/access-policies': {
      id: '/_authenticated/access-policies'
      path: '/access-policies'
      fullPath: '/access-policies'
      preLoaderRoute: typeof AuthenticatedAccessPoliciesRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/account': {
      id: '/_authenticated/account'
      path: '/account'
      fullPath: '/account'
      preLoaderRoute: typeof AuthenticatedAccountRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/certificates': {
      id: '/_authenticated/certificates'
      path: '/certificates'
      fullPath: '/certificates'
      preLoaderRoute: typeof AuthenticatedCertificatesRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/proxy-access-logs': {
      id: '/_authenticated/proxy-access-logs'
      path: '/proxy-access-logs'
      fullPath: '/proxy-access-logs'
      preLoaderRoute: typeof AuthenticatedProxyAccessLogsRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/proxy-hosts': {
      id: '/_authenticated/proxy-hosts'
      path: '/proxy-hosts'
      fullPath: '/proxy-hosts'
      preLoaderRoute: typeof AuthenticatedProxyHostsRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/redirect-hosts': {
      id: '/_authenticated/redirect-hosts'
      path: '/redirect-hosts'
      fullPath: '/redirect-hosts'
      preLoaderRoute: typeof AuthenticatedRedirectHostsRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/roles': {
      id: '/_authenticated/roles'
      path: '/roles'
      fullPath: '/roles'
      preLoaderRoute: typeof AuthenticatedRolesRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/users': {
      id: '/_authenticated/users'
      path: '/users'
      fullPath: '/users'
      preLoaderRoute: typeof AuthenticatedUsersRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_public/accept-invite': {
      id: '/_public/accept-invite'
      path: '/accept-invite'
      fullPath: '/accept-invite'
      preLoaderRoute: typeof PublicAcceptInviteRouteImport
      parentRoute: typeof PublicRouteRoute
    }
    '/_public/forgot-password': {
      id: '/_public/forgot-password'
      path: '/forgot-password'
      fullPath: '/forgot-password'
      preLoaderRoute: typeof PublicForgotPasswordRouteImport
      parentRoute: typeof PublicRouteRoute
    }
    '/_public/login': {
      id: '/_public/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof PublicLoginRouteImport
      parentRoute: typeof PublicRouteRoute
    }
    '/_public/reset-password': {
      id: '/_public/reset-password'
      path: '/reset-password'
      fullPath: '/reset-password'
      preLoaderRoute: typeof PublicResetPasswordRouteImport
      parentRoute: typeof PublicRouteRoute
    }
    '/_public/setup': {
      id: '/_public/setup'
      path: '/setup'
      fullPath: '/setup'
      preLoaderRoute: typeof PublicSetupRouteImport
      parentRoute: typeof PublicRouteRoute
    }
    '/health/live': {
      id: '/health/live'
      path: '/health/live'
      fullPath: '/health/live'
      preLoaderRoute: typeof HealthLiveRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/health/ready': {
      id: '/health/ready'
      path: '/health/ready'
      fullPath: '/health/ready'
      preLoaderRoute: typeof HealthReadyRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_public/login/': {
      id: '/_public/login/'
      path: '/'
      fullPath: '/login/'
      preLoaderRoute: typeof PublicLoginIndexRouteImport
      parentRoute: typeof PublicLoginRoute
    }
    '/_public/login/two-factor': {
      id: '/_public/login/two-factor'
      path: '/two-factor'
      fullPath: '/login/two-factor'
      preLoaderRoute: typeof PublicLoginTwoFactorRouteImport
      parentRoute: typeof PublicLoginRoute
    }
    '/media/avatars/$userId': {
      id: '/media/avatars/$userId'
      path: '/media/avatars/$userId'
      fullPath: '/media/avatars/$userId'
      preLoaderRoute: typeof MediaAvatarsUserIdRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

interface AuthenticatedRouteRouteChildren {
  AuthenticatedAccessPoliciesRoute: typeof AuthenticatedAccessPoliciesRoute
  AuthenticatedAccountRoute: typeof AuthenticatedAccountRoute
  AuthenticatedCertificatesRoute: typeof AuthenticatedCertificatesRoute
  AuthenticatedProxyAccessLogsRoute: typeof AuthenticatedProxyAccessLogsRoute
  AuthenticatedProxyHostsRoute: typeof AuthenticatedProxyHostsRoute
  AuthenticatedRedirectHostsRoute: typeof AuthenticatedRedirectHostsRoute
  AuthenticatedRolesRoute: typeof AuthenticatedRolesRoute
  AuthenticatedUsersRoute: typeof AuthenticatedUsersRoute
  AuthenticatedIndexRoute: typeof AuthenticatedIndexRoute
}

const AuthenticatedRouteRouteChildren: AuthenticatedRouteRouteChildren = {
  AuthenticatedAccessPoliciesRoute: AuthenticatedAccessPoliciesRoute,
  AuthenticatedAccountRoute: AuthenticatedAccountRoute,
  AuthenticatedCertificatesRoute: AuthenticatedCertificatesRoute,
  AuthenticatedProxyAccessLogsRoute: AuthenticatedProxyAccessLogsRoute,
  AuthenticatedProxyHostsRoute: AuthenticatedProxyHostsRoute,
  AuthenticatedRedirectHostsRoute: AuthenticatedRedirectHostsRoute,
  AuthenticatedRolesRoute: AuthenticatedRolesRoute,
  AuthenticatedUsersRoute: AuthenticatedUsersRoute,
  AuthenticatedIndexRoute: AuthenticatedIndexRoute,
}

const AuthenticatedRouteRouteWithChildren =
  AuthenticatedRouteRoute._addFileChildren(AuthenticatedRouteRouteChildren)

interface PublicLoginRouteChildren {
  PublicLoginTwoFactorRoute: typeof PublicLoginTwoFactorRoute
  PublicLoginIndexRoute: typeof PublicLoginIndexRoute
}

const PublicLoginRouteChildren: PublicLoginRouteChildren = {
  PublicLoginTwoFactorRoute: PublicLoginTwoFactorRoute,
  PublicLoginIndexRoute: PublicLoginIndexRoute,
}

const PublicLoginRouteWithChildren = PublicLoginRoute._addFileChildren(
  PublicLoginRouteChildren,
)

interface PublicRouteRouteChildren {
  PublicAcceptInviteRoute: typeof PublicAcceptInviteRoute
  PublicForgotPasswordRoute: typeof PublicForgotPasswordRoute
  PublicLoginRoute: typeof PublicLoginRouteWithChildren
  PublicResetPasswordRoute: typeof PublicResetPasswordRoute
  PublicSetupRoute: typeof PublicSetupRoute
}

const PublicRouteRouteChildren: PublicRouteRouteChildren = {
  PublicAcceptInviteRoute: PublicAcceptInviteRoute,
  PublicForgotPasswordRoute: PublicForgotPasswordRoute,
  PublicLoginRoute: PublicLoginRouteWithChildren,
  PublicResetPasswordRoute: PublicResetPasswordRoute,
  PublicSetupRoute: PublicSetupRoute,
}

const PublicRouteRouteWithChildren = PublicRouteRoute._addFileChildren(
  PublicRouteRouteChildren,
)

const rootRouteChildren: RootRouteChildren = {
  AuthenticatedRouteRoute: AuthenticatedRouteRouteWithChildren,
  PublicRouteRoute: PublicRouteRouteWithChildren,
  HealthLiveRoute: HealthLiveRoute,
  HealthReadyRoute: HealthReadyRoute,
  MediaAvatarsUserIdRoute: MediaAvatarsUserIdRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
