export type AuthDomainErrorCode =
    | 'authentication_required'
    | 'email_conflict'
    | 'invalid_email'
    | 'invalid_input'
    | 'last_active_owner'
    | 'owner_required'
    | 'password_policy'
    | 'permission_denied'
    | 'reauthentication_required'
    | 'role_in_use'
    | 'role_not_found'
    | 'service_unavailable'
    | 'system_role_immutable'
    | 'unknown_permission'
    | 'unknown_role'
    | 'user_not_active'
    | 'user_not_found'
